services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server --bind 0.0.0.0 --baseURL http://localhost:8080 --watch --disableFastRender
    volumes:
      - "./hugo:/src"
      - "./static:/app/static" # Монтирование для отслеживания изменений
    ports:
      - "1313:1313"
    networks:
      - mylocal

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    volumes:
      - "./static:/app/static" # Общий volume для Hugo и Proxy
    ports:
      - "8080:8080"
    depends_on:
      - hugo
    networks:
      - mylocal

networks:
  mylocal:
    driver: bridge